### ISSUE TITLE
Games listing - always fill the full line is their are more games to display

### ISSUE THREAD

**Issue by CamilleLetang** [Games-of-Switzerland/gos-website#36]
<img width="1429" alt="Capture d’écran 2020-11-07 à 10 32 05" src="https://user-images.githubusercontent.com/27284929/98437675-7d321a80-20e4-11eb-99e0-404529a4fbd7.png">

**Comment by tonifisler** [comment]
I can't do that, the API sends me a fixed number of items. So either you have a wide screen and there is one missing (24 items on 5 columns), or you have a smaller screen and you have one too many items (25 items on 4,3,2 columns). I chose 24 since it covers a wider range.
