### ISSUE TITLE
Can't add a game

### ISSUE THREAD

**Issue by CamilleLetang** [Games-of-Switzerland/gos-website#48]
<img width="1234" alt="Capture d’écran 2020-11-07 à 11 42 24" src="https://user-images.githubusercontent.com/27284929/98438972-7a3c2780-20ee-11eb-9e2b-f048528f27c4.png">

**Comment by CamilleLetang** [comment]
J'ai juste rempli les champs normalement - aucun autre message s'affiche

**Comment by CamilleLetang** [comment]
ça fait ça du coup : https://gos.museebolo.ch/games/mon-super-jeu-pour-faire-des-tests-1

**Comment by WengerK** [comment]
it was not an issue about games creation. it's just the redirection to the frontend url which was not configured. instead of https://staging-gos.museebolo.ch/ it was https://gos.museebolo.ch/
