### ISSUE TITLE
Create the email contact@swissgames.garden and add it to the "mail:to" on the contact page

### ISSUE THREAD

**Issue by CamilleLetang** [Games-of-Switzerland/gos-website#67]

**Comment by CamilleLetang** [comment]
I asked on Telegram, I saw you did too. You can redirect to david.javet@gmail.com for the moment
Thank you

**Comment by WengerK** [comment]
done

<img width="1577" alt="Screenshot 2021-08-30 at 11 17 58" src="https://user-images.githubusercontent.com/1841592/131316936-487361ec-2dca-401f-981d-bc0c052dfdeb.png">

**Comment by CamilleLetang** [comment]
Landed in the spam, but works.
